{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mogo.renter",
    "module": "facedetec",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "m5pq2kzfbjcoba6z5omv6itn7a"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.alipay.android.phone.zoloz",
          "module": "sdk",
          "version": {
            "requires": "3.0.0.00000001"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.alipay.android.phone",
          "module": "deviceid-release",
          "version": {
            "requires": "6.0.2.20171228"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "deviceid-release",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "facedetec-1.0.0.aar",
          "url": "facedetec-1.0.0.aar",
          "size": 7285,
          "sha512": "437705d0e81120a9ee82fffa862d926b09f851314c85a2972043b64e8c296ceb71de323004983a6c7e4aad0b6f3fa271601deb1d53dc18abb1ea699c2f700b74",
          "sha256": "0e9f2990841ffa5afce37170285c78e5674723c9f9fd42a15824b7ea546c451a",
          "sha1": "ac4f9302d7db523363c20a70c3674faee865cf30",
          "md5": "c5a2105e0b5ec2d3cff2dd16f8971daa"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.alipay.android.phone.zoloz",
          "module": "sdk",
          "version": {
            "requires": "3.0.0.00000001"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.alipay.android.phone",
          "module": "deviceid-release",
          "version": {
            "requires": "6.0.2.20171228"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "deviceid-release",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "facedetec-1.0.0.aar",
          "url": "facedetec-1.0.0.aar",
          "size": 7285,
          "sha512": "437705d0e81120a9ee82fffa862d926b09f851314c85a2972043b64e8c296ceb71de323004983a6c7e4aad0b6f3fa271601deb1d53dc18abb1ea699c2f700b74",
          "sha256": "0e9f2990841ffa5afce37170285c78e5674723c9f9fd42a15824b7ea546c451a",
          "sha1": "ac4f9302d7db523363c20a70c3674faee865cf30",
          "md5": "c5a2105e0b5ec2d3cff2dd16f8971daa"
        }
      ]
    }
  ]
}
