{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mogo.renter",
    "module": "base",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "fe7gb252vvctrhgerlspg4jyie"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-android-no-op",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0-alpha01"
          }
        },
        {
          "group": "androidx.transition",
          "module": "transition",
          "version": {
            "requires": "1.1.0-alpha01"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0-alpha01"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.0-alpha2"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0-alpha01"
          }
        },
        {
          "group": "androidx.palette",
          "module": "palette",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.1.65.android"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.wdullaer",
          "module": "materialdatetimepicker",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.eowise",
          "module": "recyclerview-stickyheaders",
          "version": {
            "requires": "0.5.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "recyclerview-stickyheaders",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.liulishuo.filedownloader",
          "module": "library",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.tbruyelle.rxpermissions2",
          "module": "rxpermissions",
          "version": {
            "requires": "0.9.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "rxpermissions",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.yalantis",
          "module": "ucrop",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.amap.api",
          "module": "3dmap",
          "version": {
            "requires": "latest.integration"
          }
        },
        {
          "group": "com.amap.api",
          "module": "location",
          "version": {
            "requires": "latest.integration"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "2.9.44"
          }
        },
        {
          "group": "com.scwang.smartrefresh",
          "module": "SmartRefreshLayout",
          "version": {
            "requires": "1.1.0-alpha-14"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "com.mgzf.sdk",
          "module": "mgsdk",
          "version": {
            "requires": "0.2.7-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.security",
          "module": "mgapisecurity",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.mgzf.android.aladdin",
          "module": "aladdin",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.lib",
          "module": "lib_payment",
          "version": {
            "requires": "0.5.0-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.partner",
          "module": "mgutils",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.hybrid",
          "module": "mgfilechooser",
          "version": {
            "requires": "0.3.7-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.hybrid",
          "module": "mgjsservice",
          "version": {
            "requires": "0.3.7-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.hybrid",
          "module": "mgwebkit",
          "version": {
            "requires": "0.3.7-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.hybrid",
          "module": "mgbluetooth",
          "version": {
            "requires": "0.3.7-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.hybrid",
          "module": "mgscancode",
          "version": {
            "requires": "0.3.7-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.widget",
          "module": "mgitem",
          "version": {
            "requires": "0.0.10-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.widget",
          "module": "mglineview",
          "version": {
            "requires": "0.0.10-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.widget",
          "module": "mgbottomwheel",
          "version": {
            "requires": "0.3.2-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.widget",
          "module": "mgsplashview",
          "version": {
            "requires": "0.0.10-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.widget",
          "module": "mgflowlayout",
          "version": {
            "requires": "0.1.21"
          }
        },
        {
          "group": "com.mgzf.widget",
          "module": "mgbanner",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.widget",
          "module": "mgfilterdownview",
          "version": {
            "requires": "0.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.widget",
          "module": "mglinkedlist",
          "version": {
            "requires": "0.4.2-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.widget",
          "module": "mgmultistatus",
          "version": {
            "requires": "0.4.4-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "base-1.0.0.aar",
          "url": "base-1.0.0.aar",
          "size": 370627,
          "sha512": "21da321408a0fe8f6115158289cf934fdd83c0f9c2ae37fe608db244a9978f615b765f6cfa45c8c84b85a675b8d39a2ba91f0d9df4b66791b9fb77eaba5db4f3",
          "sha256": "58b8f79dfdcc851258bc95d50a4ed56183ba6d8a39644b67a8f6c9ba92d8c00a",
          "sha1": "d9eeb104379e50d02822f149621e7447d6e7d7fc",
          "md5": "d5d67af6b0a312659d6ad211bcfcfb15"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-android-no-op",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0-alpha01"
          }
        },
        {
          "group": "androidx.transition",
          "module": "transition",
          "version": {
            "requires": "1.1.0-alpha01"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0-alpha01"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.0-alpha2"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0-alpha01"
          }
        },
        {
          "group": "androidx.palette",
          "module": "palette",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.1"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.1.65.android"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.wdullaer",
          "module": "materialdatetimepicker",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.eowise",
          "module": "recyclerview-stickyheaders",
          "version": {
            "requires": "0.5.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "recyclerview-stickyheaders",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.liulishuo.filedownloader",
          "module": "library",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.tbruyelle.rxpermissions2",
          "module": "rxpermissions",
          "version": {
            "requires": "0.9.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "rxpermissions",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.yalantis",
          "module": "ucrop",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.amap.api",
          "module": "3dmap",
          "version": {
            "requires": "latest.integration"
          }
        },
        {
          "group": "com.amap.api",
          "module": "location",
          "version": {
            "requires": "latest.integration"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "2.9.44"
          }
        },
        {
          "group": "com.scwang.smartrefresh",
          "module": "SmartRefreshLayout",
          "version": {
            "requires": "1.1.0-alpha-14"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "com.mgzf.sdk",
          "module": "mgsdk",
          "version": {
            "requires": "0.2.7-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.security",
          "module": "mgapisecurity",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.mgzf.android.aladdin",
          "module": "aladdin",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.lib",
          "module": "lib_payment",
          "version": {
            "requires": "0.5.0-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.partner",
          "module": "mgutils",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.hybrid",
          "module": "mgfilechooser",
          "version": {
            "requires": "0.3.7-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.hybrid",
          "module": "mgjsservice",
          "version": {
            "requires": "0.3.7-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.hybrid",
          "module": "mgwebkit",
          "version": {
            "requires": "0.3.7-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.hybrid",
          "module": "mgbluetooth",
          "version": {
            "requires": "0.3.7-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.hybrid",
          "module": "mgscancode",
          "version": {
            "requires": "0.3.7-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.widget",
          "module": "mgitem",
          "version": {
            "requires": "0.0.10-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.widget",
          "module": "mglineview",
          "version": {
            "requires": "0.0.10-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.widget",
          "module": "mgbottomwheel",
          "version": {
            "requires": "0.3.2-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.widget",
          "module": "mgsplashview",
          "version": {
            "requires": "0.0.10-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.widget",
          "module": "mgflowlayout",
          "version": {
            "requires": "0.1.21"
          }
        },
        {
          "group": "com.mgzf.widget",
          "module": "mgbanner",
          "version": {
            "requires": "0.3.3-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.widget",
          "module": "mgfilterdownview",
          "version": {
            "requires": "0.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.widget",
          "module": "mglinkedlist",
          "version": {
            "requires": "0.4.2-SNAPSHOT"
          }
        },
        {
          "group": "com.mgzf.widget",
          "module": "mgmultistatus",
          "version": {
            "requires": "0.4.4-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "base-1.0.0.aar",
          "url": "base-1.0.0.aar",
          "size": 370627,
          "sha512": "21da321408a0fe8f6115158289cf934fdd83c0f9c2ae37fe608db244a9978f615b765f6cfa45c8c84b85a675b8d39a2ba91f0d9df4b66791b9fb77eaba5db4f3",
          "sha256": "58b8f79dfdcc851258bc95d50a4ed56183ba6d8a39644b67a8f6c9ba92d8c00a",
          "sha1": "d9eeb104379e50d02822f149621e7447d6e7d7fc",
          "md5": "d5d67af6b0a312659d6ad211bcfcfb15"
        }
      ]
    }
  ]
}
