{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mogo.renter",
    "module": "wallet",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "s3eoxmpmpvd5fpsarxyi3uadvm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "wallet-1.0.0.aar",
          "url": "wallet-1.0.0.aar",
          "size": 313560,
          "sha512": "10daef4bfcaa6570dbcbd737d95f53e5ccfdfe2d36a91cc8c097ff5253dda8b39e4e3cdcc7bc6e49dca5453f5bbf02fe7bab49d510b7dbb37c8cd3149ca64697",
          "sha256": "2c008c9b6f27e3a843ddb39825b69d8240ac93dcb60d373bfa9e532209883e51",
          "sha1": "0cc310e892816f2cf439fa37229604efee646391",
          "md5": "54658185522dbae3a00afedb8cdcdb68"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mogo.renter",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.mogo.renter",
          "module": "api",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "wallet-1.0.0.aar",
          "url": "wallet-1.0.0.aar",
          "size": 313560,
          "sha512": "10daef4bfcaa6570dbcbd737d95f53e5ccfdfe2d36a91cc8c097ff5253dda8b39e4e3cdcc7bc6e49dca5453f5bbf02fe7bab49d510b7dbb37c8cd3149ca64697",
          "sha256": "2c008c9b6f27e3a843ddb39825b69d8240ac93dcb60d373bfa9e532209883e51",
          "sha1": "0cc310e892816f2cf439fa37229604efee646391",
          "md5": "54658185522dbae3a00afedb8cdcdb68"
        }
      ]
    }
  ]
}
